### Site Settings ###
title               : nairdah
description         : i sometime take pics in games...
url                 : nairdah.me
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
remote_theme        : YoussefRaafatNasry/portfolYOU
logo                : /assets/avatar-round.png


### Plugins ###
plugins:
  - jemoji
  - jekyll-seo-tag


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md



### Author Info ###
author:
# name              : Adrian
# image             : 
# behance           : your_username
# dribbble          : your_username
  email             : hello@nairdah.me
# facebook          : adrian28
  github            : nairdahh
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
# linkedin          : your_username
# medium            : your_username
# soundcloud        : your_username
  spotify           : adriannn28
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : nairdah28
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
  bluesky           : nairdah.bsky.social

  url               : https://nairdah.me/





### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-0HBKDVWV36


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


sass:
  style: compressed

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
